name: Create spotify helper

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        working-directory: HelperProjects/SpotifyTokenHelper
        run: dotnet restore

      - name: Build self-contained Windows EXE
        working-directory: HelperProjects/SpotifyTokenHelper
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-helper-windows-self-contained-exe
          path: HelperProjects/SpotifyTokenHelper/bin/Release/net*/win-x64/publish/

      - name: Build self-contained Linux executable
        working-directory: HelperProjects/SpotifyTokenHelper
        run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-helper-linux-self-contained
          path: HelperProjects/SpotifyTokenHelper/bin/Release/net*/linux-x64/publish/
