name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up buildx action
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Check Docker Buildx version
        run: docker buildx version

      - name: Set up buildx builder
        run: docker buildx create --use

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CalendarView/CalendarView.Web/Dockerfile
          push: true
          tags: arizonagreentea0905/acal:${{ github.ref_name }}
          buildkit: true
